name: Generate Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and publish Unity API docs
    steps:
    - uses: actions/checkout@v1
    # ...
    - uses: embrace-io/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx_project/docfx.json
    # Publish generated site using GitHub Pages
    - uses: embrace-io/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: docfx_project/_site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
